# Generated by Django 4.2.5 on 2023-09-20 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circle', '0002_remove_member_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('dress_code', models.CharField(max_length=255)),
                ('event_status', models.CharField(choices=[('Happening', 'Happening'), ('Postponed', 'Postponed'), ('Cancelled', 'Cancelled')], default='Happening', max_length=10)),
                ('guests', models.ManyToManyField(related_name='events_attending', to='circle.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_status', models.CharField(choices=[('Attending', 'Attending'), ('Not Attending', 'Not Attending'), ('Undecided', 'Undecided')], default='Undecided', max_length=15)),
                ('guest_count', models.PositiveBigIntegerField(default=1)),
                ('dietary_preferences', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.member')),
            ],
        ),
    ]
