# Generated by Django 4.2.5 on 2023-09-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='phone_number',
        ),
    ]
