# Generated by Django 4.2.5 on 2023-09-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_remove_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', to='circle.member'),
        ),
    ]
