# Generated by Django 4.2.6 on 2023-11-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0003_alter_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='img/defaults/default_profile_pic.png', upload_to='member_images/'),
        ),
    ]
