# Generated by Django 4.2.5 on 2023-09-22 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circle', '0002_remove_member_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('list_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('receivers', models.ManyToManyField(related_name='lists_received', to='circle.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_image', models.ImageField(default='', upload_to='list_items/')),
                ('item_url', models.URLField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.list')),
            ],
        ),
        migrations.CreateModel(
            name='CheckedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_status', models.CharField(choices=[('Unchecked', 'Unchecked'), ('Checked', 'Checked')], default='Unchecked', max_length=15)),
                ('list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.listitem')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.member')),
            ],
        ),
    ]
