# Generated by Django 4.2.5 on 2023-09-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CheckedItem',
        ),
    ]
