# Generated by Django 4.2.5 on 2023-10-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_checkitemnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
