# Generated by Django 4.2.6 on 2023-11-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_list_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='item_image',
            field=models.ImageField(null=True, upload_to='list_items/'),
        ),
    ]
