# Generated by Django 4.2.5 on 2023-10-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
